														-- METRICS

create table if not exists metrics (
id int generated by default as identity not null primary key,
metric_group varchar(255) not null,
value float(5) not null,
create_time timestamp not null
);