														-- METRICS

create table if not exists metrics (
id int generated by default as identity not null primary key,
name varchar(255) not null,
description varchar(255) not null,
is_exception boolean not null default false,
create_time timestamp not null
);

create index if not exists id_index ON metrics (id);